name: Create releases
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: "@rowanmanning/wikilike"
          changelog-type: github
          prerelease: true
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
